// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SeckillClient is the client API for Seckill service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeckillClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type seckillClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillClient(cc grpc.ClientConnInterface) SeckillClient {
	return &seckillClient{cc}
}

var seckillCallStreamDesc = &grpc.StreamDesc{
	StreamName: "Call",
}

func (c *seckillClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/seckill.Seckill/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillService is the service API for Seckill service.
// Fields should be assigned to their respective handler implementations only before
// RegisterSeckillService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type SeckillService struct {
	Call func(context.Context, *Request) (*Response, error)
}

func (s *SeckillService) call(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/seckill.Seckill/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterSeckillService registers a service implementation with a gRPC server.
func RegisterSeckillService(s grpc.ServiceRegistrar, srv *SeckillService) {
	srvCopy := *srv
	if srvCopy.Call == nil {
		srvCopy.Call = func(context.Context, *Request) (*Response, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "seckill.Seckill",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Call",
				Handler:    srvCopy.call,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "proto/seckill.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewSeckillService creates a new SeckillService containing the
// implemented methods of the Seckill service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewSeckillService(s interface{}) *SeckillService {
	ns := &SeckillService{}
	if h, ok := s.(interface {
		Call(context.Context, *Request) (*Response, error)
	}); ok {
		ns.Call = h.Call
	}
	return ns
}

// UnstableSeckillService is the service API for Seckill service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableSeckillService interface {
	Call(context.Context, *Request) (*Response, error)
}
