// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: seckill/proto/seckill.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Seckill service

func NewSeckillEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Seckill service

type SeckillService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type seckillService struct {
	c    client.Client
	name string
}

func NewSeckillService(name string, c client.Client) SeckillService {
	return &seckillService{
		c:    c,
		name: name,
	}
}

func (c *seckillService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Seckill.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Seckill service

type SeckillHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterSeckillHandler(s server.Server, hdlr SeckillHandler, opts ...server.HandlerOption) error {
	type seckill interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Seckill struct {
		seckill
	}
	h := &seckillHandler{hdlr}
	return s.Handle(s.NewHandler(&Seckill{h}, opts...))
}

type seckillHandler struct {
	SeckillHandler
}

func (h *seckillHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SeckillHandler.Call(ctx, in, out)
}
